## onex
onex:
  # App
  app:
    # 应用名称
    parent-artifact-id: @project.parent.artifactId@
    artifact-id: @project.artifactId@
    # 版本号
    version: @project.version@
    # maven编译时间
    build-time: @maven.build.timestamp@
  # 过滤器
  filter:
    enable: true
  # shiro
  shiro:
    enable: true
  # mybatis配置
  mybatisplus:
    enable: true
  # swagger
  swagger:
    enable: false
  # WebMVC
  webmvc:
    enable: true
  # async
  async:
    enable: false
  # 登录配置
  auth:
    ## 权限控制扫描包
    access-scan-package: com.nb6868.onex.portal.modules
    settings:
      admin:
        register: false
        forget-password: false
        types:
          - ADMIN_USERNAME_PASSWORD
    configs:
      ## 后台-帐号密码登录
      ADMIN_USERNAME_PASSWORD:
        type: ADMIN_USERNAME_PASSWORD
        multi-login: true
  # 存储配置
  oss:
    enable: true
    configs:
      OSS_PUBLIC:
        type: aliyun
        domain: https://xxx.oss-cn-hangzhou.aliyuncs.com/
        prefix: xxx
        endPoint: http://oss-cn-hangzhou.aliyuncs.com/
        accessKeyId: xxx
        accessKeySecret: xxx
        bucketName: xxx
        keepFileName: false
