# Tomcat
server:
  tomcat:
    # 配置tomcat的临时目录
    basedir: /home/onex/temp
  port: 18181
  servlet:
    context-path: /portal-api

spring:
  application:
    name: portal-api
  # 环境 dev|test|prod
  profiles:
    active: common,sched,onex,dev

# mybatis plus
# see {https://mybatis.plus/config/}
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.nb6868.onex.portal.modules.*.entity
  # 枚举扫描
  typeEnumsPackage: com.nb6868.onex.portal.modules.*.enums
