## onex
onex:
  # App
  app:
    # 应用名称
    parent-artifact-id: @project.parent.artifactId@
    artifact-id: @project.artifactId@
    # 版本号
    version: @project.version@
    # maven编译时间
    build-time: @maven.build.timestamp@
  # 过滤器
  filter:
    enable: true
  # shiro
  shiro:
    enable: true
    type: jwt
  # mybatis配置
  mybatisplus:
    enable: true
  # swagger
  swagger:
    enable: false
  # WebMVC
  webmvc:
    enable: true
  # async
  async:
    enable: false
  # 自动填充
  auto-fill:
    enable: true
  # 异常处理
  exception-handler:
    enable: true
    detail-msg: false
  # 日志
  aspect:
    log: true
  log:
    enable: true
    # 存储方式
    type: db
  # 数据查询过滤
  data-query-filter:
    enable: true
  # oss
  oss:
    # 文件请求路径
    file-request-path:
    # 文件存储路径,以/结尾
    file-storage-path:
  # 登录配置
  auth:
    # 访问控制
    access-control:
      enable: true
      # 扫描包
      scan-package: com.nb6868.onex.common.controller,com.nb6868.onex.uc.controller,com.nb6868.onex.sys.controller,com.nb6868.onex.portal.modules
    configs:
      ## 后台-帐号密码登录
      ADMIN_USERNAME_PASSWORD:
        type: ADMIN_USERNAME_PASSWORD
        multi-login: true
