# Tomcat
server:
  tomcat:
    # 配置tomcat的临时目录
    basedir: /www/wwwroot/onex/shop-api/temp
  port: 19003
  servlet:
    context-path: /onex-shop-api

knife4j:
  # 生产环境开启访问认证
  basic:
    enable: true
    username: shop-api
    password: shop-api@2021

spring:
  datasource:
    dynamic:
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://hw3.nb6868.com:3306/onex?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
          username: onex
          password: CWCPxhpp67yaErnn
          druid:
            initial-size: 5
