# Tomcat
server:
  tomcat:
    # 配置tomcat的临时目录
    basedir: /www/wwwroot/onex/shop-api/temp
  port: 9003
  servlet:
    context-path: /shop-api

spring:
  application:
    name: shop-api
  # 环境 dev|prod
  profiles:
    active: common,onex,dev
  # spring cache
  cache:
    type: simple

# mybatis plus
# see {https://mybatis.plus/config/}
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.nb6868.onex.modules.*.entity,com.nb6868.onex.shop.modules.*.entity
  # 枚举扫描
  # typeEnumsPackage: com.nb6868.onex.modules.*.enums
