# Tomcat
server:
  tomcat:
    # 配置tomcat的临时目录
    basedir: /home/onex/temp
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
  port: 18181
  servlet:
    context-path: /onex-boot-api
    session:
      cookie:
        http-only: true

spring:
  # 环境 dev|test|prod
  profiles:
    active: onex,dev
  messages:
    encoding: UTF-8
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  # 自定义404
  mvc:
    # 出现错误时, 直接抛出异常
    throw-exception-if-no-handler-found: true
  # freemarker
  freemarker:
    suffix: .html
    request-context-attribute: ctx
  web:
    resources:
      # 不为工程中的资源文件建立映射
      add-mappings: false
  # fix easypoi duplicated bean issue
  main:
    allow-bean-definition-overriding: true
  # spring cache
  cache:
    type: simple
  # quartz 定时任务
  quartz:
    ## 任务存储方式
    job-store-type: jdbc

# mybatis plus
# see {https://mybatis.plus/config/}
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.nb6868.onex.api.modules.*.entity
  # 枚举扫描
  typeEnumsPackage: com.nb6868.onex.api.modules.*.enums
  global-config:
    # 数据库相关配置
    db-config:
      # 主键类型
      id-type: ASSIGN_ID
      # 字段策略
      insert-strategy: NOT_NULL
      update-strategy: NOT_NULL
      # 逻辑删除配置
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    # 关闭mp3.0自带的banner
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
